language: node_js
node_js:
 - "node"
sudo: required
services:
 - "docker"
before_script:
 - npm install
before_install:
 - sudo docker run --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
 - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
 - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
 - export BUILDKIT_HOST=tcp://0.0.0.0:1234
script:
 - npm test
after_success:
 - bash ./travisBuild.sh
  #- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
 #- docker tag app $DOCKER_USER/app:$TRAVIS_BUILD_NUMBER
 #- docker push $DOCKER_USER/app:$TRAVIS_BUILD_NUMBER
 #- docker tag app $DOCKER_USER/app:latest
 #- docker push $DOCKER_USER/app:latest
