language: node_js
node_js:
 - "node"
sudo: required
services:
 - "docker"
before_script:
 - npm install
script:
 - npm test
after_success:
 - echo $TRAVIS_COMMIT
 - echo $TRAVIS_TAG
 - echo $TRAVIS_BRANCH
 - if [ $TRAVIS_BRANCH = "master" ];
   then bash ./travisBuild.sh;
   fi
