language: node_js
node_js:
 - "node"
sudo: required
services:
 - "docker"
before_script:
 - npm install
before_install:
script:
 - npm test
after_success:
 - npm run prod-build
 - bash ./travisBuild.sh
