language: node_js
node_js:
 - "node"
sudo: required
services:
 - "docker"
before_script:
 - npm install
script:
 - npm test
after_success:
 - if [[ $TRAVIS_BRANCH = "master" ]];
   then bash ./travisBuild.sh;
   fi
