# changed to slim for debug
FROM raspbian/stretch

RUN apt-get update -y
RUN wget https://nodejs.org/dist/latest-dubnium/node-v10.20.1-linux-armv6l.tar.xz
RUN tar -xJf node-v10.20.1-linux-armv6l.tar.xz

RUN apt-get install rsync -y
RUN rsync -av /node-v10.20.1-linux-armv6l/* /usr/local/

RUN apt-get update
RUN apt-get install chromium-browser chromium-codecs-ffmpeg -y
RUN apt-get --fix-broken install


RUN mkdir -p /usr/src/app
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package and lock is copied
COPY package*.json ./

# Bundle app source
COPY . .

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
ENV CHROME_BIN="/usr/bin/chromium-browser"

RUN npm install && npm run prod-build

# Expose 3000 and then map at runtime to a different port
# docker run -p 8080:3000 -d lnicdockerhub/app:latest-travis
EXPOSE 3000

CMD [ "node", "dist/app" ]